### ISSUE TITLE
Support downloading "dev" for a certain release

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-dts#2]
I'd like to be able to say `vscode-dts dev 1.36` to make sure I get a proposed .dts which is compatible with my vscode.d.ts. The one from master is not guaranteed to be compatible with the vscode.d.ts from a release. This is probably mainly just useful for people like me who are actually shipping an extension that uses proposed, not just using those APIs for development.

**Comment by octref** [comment]
In next version you can use `npx vscode-dts dev <git-tag | git-branch>`.
